spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://113.200.91.62:5432/postgres
    username: postgres
    password: postgres
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: irs-inventory
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  profiles:
    active: qa

server:
  port: 8000
  context-path: /irs-inventory
mybatis:
  check-config-location: true
  config-location: classpath:mybatis/mybatis-config.xml
  
#logging:
#  config: classpath:logback-spring.xml